# must accept EULA the first time that the image is started
# docker run splunk/splunk:6.5.2
# Options on how to review the EULA and accept it: 
# 1. docker run -it splunk/splunk:6.5.2
# 2. Add the following environment variable: SPLUNK_START_ARGS=--accept-license
# e.g., docker run -e "SPLUNK_START_ARGS=--accept-license" splunk/splunk 

# Support for Docker Compose v2, https://docs.docker.com/compose/overview/
version: '2'
services:
  vsplunk:
    image: busybox
    volumes:
      - /opt/splunk/etc
      - /opt/splunk/var
  vsplunk_uf:
    image: busybox
    volumes:
      - /opt/splunk/etc
      - /opt/splunk/var

  splunkenterprise:
    hostname: splunkenterprise
#    image: splunk/splunk:6.5.2-monitor
    image: splunk/splunk:6.6.1-monitor
    environment:
      SPLUNK_START_ARGS: --accept-license --answer-yes
      SPLUNK_ENABLE_LISTEN: 9997
      SPLUNK_ADD: tcp 1514
      SPLUNK_USER: root
    volumes_from:
      - vsplunk
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"
    volumes:
      - /var/lib/docker/containers:/host/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring

  splunkuniversalforwarder:
    hostname: splunkuniversalforwarder
    #image: splunk/universalforwarder:6.5.2
    image: splunk/universalforwarder:6.6.1-monitor
    links:
      - splunkenterprise
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_FORWARD_SERVER: splunkenterprise:9997
      SPLUNK_USER: root
    volumes_from:
      - vsplunk_uf
    ports:
      - "9000:8000"
    volumes:
      - /var/lib/docker/containers:/host/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - monitoring

  wordpress_db:
    image: mariadb
    hostname: wordpressdb
    links:
      - splunkenterprise
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
    labels:
      - "sdlc=dev"
    logging:
      driver: splunk
      options:
#        splunk-url: "https://172.20.0.2:8088"
#        splunk-url: "https://splunkenterprise:8088"
#        splunk-url: "https://dockermonitoringconf2017_splunkenterprise_1:8088"
#        splunk-url: "https://localhost:8088"
        splunk-url: "https://127.0.0.1:8088"
        splunk-token: "00000000-0000-0000-0000-000000000000"
        splunk-insecureskipverify: "true"
#        splunk-source: wordpressdb
        tag: "{{.Name}}"
        labels: sdlc
        env: "MYSQL_ROOT_PASSWORD"
#        splunk-verify-connection: "false"
# version: '1'
#    log_driver: "splunk"
#    log_opt:
#          splunk-url: "https://splunkenterprise:8088"
#          splunk-token: "00000000-0000-0000-0000-000000000000"
#          splunk-insecureskipverify: "true"
#          splunk-source: wordpressdb
#          tag: "{{.Name}}"
#          labels: sdlc
#          env: "MYSQL_ROOT_PASSWORD"
    networks:
      - monitoring

  wordpress:
    hostname: wordpress
    image: wordpress
    links:
      - wordpress_db
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_PASSWORD: my-secret-pw
    labels:
      - "sdlc=dev"
    networks:
      - monitoring

networks:
  monitoring:
#    driver: bridge
